### ISSUE TITLE
v2

### ISSUE THREAD

**Issue by sebastiandedeyne** [spatie-custom/blender.js#6]
Ideas and progress tracking for `blender.js@2.0`
- [ ] Rename to `blender-js`
- [ ] Modules shouldn't do anything, just export functionality...
- [ ] ...Some sort of bootstrap file would be ok, e.g. for registering the csrf header
- [ ] No more global `ß`
- [ ] Embrace ES6, modify code to follow our style guide
- [ ] Expose everything through `index`, so we don't need to import paths in our projects
## Deprecate modules
- [ ] Form autosave
## Extract modules
- [ ] Confirm: would be nice to make this reusable outside of Blender
## Translations & locales
- [ ] Clean up locales so that they're not global anymore

**Comment by sebastiandedeyne** [comment]
Use Vue components for form, these should be enough to start:

- [ ] `blender-text`
- [ ] `blender-date`
- [ ] `blender-textarea`
- [ ] `blender-redactor`
- [ ] `blender-checkbox`
- [ ] `blender-dropdown`

Example usage:

```html
<blender-textarea
    label="Tekst"
    name="text"
    value="old('text', $model->text)"
></blender-textarea>
```

Or translated...

```html
<blender-textarea
    label="Tekst"
    name="text"
    locale="nl"
    value="old('translated_text_nl', $model->getTranslation('nl', 'text'))"
></blender-textarea>
```

**Comment by willemvb** [comment]
Looks clean!

Details:
- [ ] Publish to `@spatie` namespace on npm
- [ ] Review/update `blender-css` for these changed modules

**Comment by freekmurze** [comment]
Looking good!
